### ISSUE TITLE
Application blocked by Virus protection

### ISSUE THREAD

**Issue by pamtenbroeke** [rspinney/Spatial-Metric-Calculator#1]
Dear Richard Spinney,

I have been trying to use the spatial metric calculator application from Github (the pre-compiled executable for windows), for my data-analysis.  However, my University Virus Protection software blocks the use of the application, as it has not been ‘signed’ by the developer.

I have a windows laptop provided by my University, so the only option for me would be to use the pre-compiled executables. 

Would you have a solution for this issue?

Thanks in advance!

Kind regards,
Pam ten Broeke

**Comment by rspinney** [comment]
Hi Pam,

Thanks for this.

So signing the executables for windows requires an on-going cost associated with generating and maintaining certificates by a third party that I am not currently set up to do.

Without anti-virus protection a warning appears, but can be dismissed. So for now I'm afraid to say my only advice is find a machine without that anti-virus software or try a different platform. 

However, I will look into the current range of code signing solutions to see if any are viable for me. If so I will sign the executables and update them here. Unfortunately I don't have a time frame for this right now.

For now I'm going to close this issue here as I am aware of the problem, however feel free to contact me outside of Github. You can email me at r [dot] spinney [at] unsw [dot] edu [dot] au.

Hopefully we can find a way to get you up and running with the software.

Thanks,

Richard.
